### ISSUE TITLE
Missing mask for whole-body generation.

### ISSUE THREAD

**Issue by Mathieu-Geisert** [MeMory-of-MOtion/hpp-loco#2]
Hi,

The submodule pg from @jcarpent  is used to generate the whole-body motion. (by the way @pFernbach, in gepgitlab.laas.fr/pfernbac/reachability/ the link to the submodule still point to Jcarpent's home folder so maybe you should fork it or link it to my repository before justin's home is deleted...).

With Anymal, I got some problems with the whole-body generation because the QP was over-constrained, even when I added masks to the tasks. It was because the masks were missing in the function "dyn_value" of classes SE3Task and COMTask in "pg/pinocchio/tasks.py". 
@jcarpent, is there a reason why this was missing for those particular tasks?

I've push my modification in my repo gepgitlab.laas.fr/mgeisert/pg but I haven't find any other repository other than /home/jcarpent/git/pattern-generator.git to do a pull request.
@jcarpent Is there a main repository for this package other than your home? If not, is it because some parts of this code should not be released?

Best,
Mathieu.

**Comment by jcarpent** [comment]
> With Anymal, I got some problems with the whole-body generation because the QP was over-constrained, even when I added masks to the tasks. It was because the masks were missing in the function "dyn_value" of classes SE3Task and COMTask in "pg/pinocchio/tasks.py".
> @jcarpent, is there a reason why this was missing for those particular tasks?

This has been fixed a while ago.

**Comment by Mathieu-Geisert** [comment]
Ok, thanks. I just saw that in the latest version, the mask is used for SE3Task, but it looks like the mask is still missing for COMTask.

I spend some time checking the repositories, and it is a bite messy:
- In package "pg", the master branch is very old (September 2015) and it looks like the newest one (August 2017) is "topic/medaille".
- In package "reachability" (from Pierre's gepgitlab), the submodule "pg" was pointing on the last commit of branch "topic/medaille", but Justin changed it to a commit that does not exist on /home/jcarpent/git/pattern-generator.git, so Pierre changed it to a commit made in November 2016, before the mask was added to SE3Task...

**Comment by jcarpent** [comment]
Just to be clear, this module has been made at the beginning of my PhD and was not aimed to be used further.
This code has been transcribed to a C++ version written by @andreadelprete and called TSID. It would better to use this library instead of my old version.

**Comment by pFernbach** [comment]
Yes, we will switch to TSID before the end of the year.
